### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by yuinacor** [line/multi-project-support#20]
1. Remove snapshot
1. commit & tagging
1. start new snapshot
    1. major/minor/patch? which kind of?
    1. May I have any flag to choose this?
    1. But generally, patch seems enough, and for major or minor, it can be triggered by milestone creation.
1. commit & push with tag
1. create release draft from a tag just pushed.
1. review draft and publish if it seems ok.
1. publish plugins to gradle plugin portal.
    1. publish to bintray would good to do also.

**Comment by yuinacor** [comment]
https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/td-p/31504/page/4

Is seems impossible to triggering any action manually.

So github action could not be a complete solution to cover automated release process.

**Comment by yuinacor** [comment]
The only way I getting over this situation is, use travis ci for manually triggering tasks.

So

1. By travis ci, prepare release.
    1. remove snapshot.
    1. commit && push.
    1. create release draft from new version.
        1. Good to generate release note automatically.
1. By maintainer, Review release draft
    1. Review release draft.
    1. Publish if there is no issue.
    1. Then tag also made by github release sequence.
    1. And release publish event will be triggered
1. By github action, publish binary to gradle plugins portal.
    1. GH Action will be triggered
    1. Then run `./gradlew publishPlugin` with stored secret.
    1. Then done.

The reason why not to use travia ci all is, wanna store secure value into github, rather than other potentially replaced.

How about next developing branch?
No idea... Just make it in manual...

HDYT @noveler17 ?

**Comment by noveler17** [comment]
For a simpler process, could you check the following flow?

1. Generally, maintain only `master` branch.
1. When PR merged, let Travis CI...
    1. Remove the recent release draft if it exists.
    1. Write a new release draft
1. Push `release` button in the draft when reviewed enough and determined to release
    * Version can be fixed at this time.
1. Let GH action package & release the latest `master` into `plugins.gradle.org`.

**Comment by yuinacor** [comment]
1. Fine at all. Just maintain master before we faced any issue about that.
2. It can be done with GH action.
3. True
4. True
